### ISSUE TITLE
Add helpers?

### ISSUE THREAD

**Issue by arockenberger** [NWU-eResearch/2020-04-22-ttt-online-CEST#1]
Hei!

I was wondering if you would be ok with updating the website to show "helpers" also. I was one of the observers/helpers during the workshop and would like to be able to refer to the website showing that.

All the best,

Annika

**Comment by NWU-eResearch** [comment]
Hi Annika, 

sure! No Problem. give mee about 10min ansd then have a look.

Regards
Martin


NWU CORONA VIRUS: http://www.nwu.ac.za/coronavirus/ 
  Vrywaringsklousule / Disclaimer: 
http://www.nwu.ac.za/it/gov-man/disclaimer.html
>>> Annika Rockenberger <notifications@github.com> 6/17/2020 11:41 AM
>>>
Hei!
I was wondering if you would be ok with updating the website to show
"helpers" also. I was one of the observers/helpers during the workshop
and would like to be able to refer to the website showing that.
All the best,
Annika
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
( https://github.com/NWU-eResearch/2020-04-22-ttt-online-CEST/issues/1)
, or unsubscribe
(

**Comment by arockenberger** [comment]
Thx!
